### ISSUE TITLE
Understanding .yaml file + csv input 

### ISSUE THREAD

**Issue by ococrook** [Jhsmit/PyHDX#302]
Hi @Jhsmit 

I'm trying to run using my own data

```py
input_dir = Path().resolve().parent.parent / 'tests' / 'test_data' / 'input'
s = yaml.safe_load((input_dir / 'data_states.yaml').read_text())
p = StateParser(state_spec=s, data_src=input_dir)
hdxm = p.load_hdxm("SecB_tetramer")
```

If I understand correctly I need to format a .yaml file and a .csv that looks roughly like a dynamX input. 

I've tried with the following yaml:

```yaml
# YAML file for loading HDX-MS data; PyHDX v0.4.0b3

Hoip_testing:
  filenames:
    - hoipsim1.csv
  FD_control:
    state: WT
    exposure:
      value: 30
      unit: s
  experiment:
    state: WT
  pH: 8.
  d_percentage: 90.
  temperature:
    value: 30.
    unit: Celsius
  sequence: GPGQECAVCGWALPHNRMQALTSCECTICPDCFRQHFTIALKEKHITDMVCPACGRPDLTDDTQLLSYFSTLDIQLRESLEPDAYALFHKKLTEGVLMRDPKFLWCAQCSFGFIYEREQLEATCPQCHQTFCVRCKRQWEEQHRGRSCEDFQNWKRMNDPEYQAQGLAMYLQENGIDCPKCKFSYALARGGCMHFHCTQCRHQFCSGCYNAFYAKNKCPEPNCRVKKSLHGHHPRDCLFYLRDWTALRLQKLLQDNNVMFNTEPPAGARAVPGGGCRVIEQKEVPNGLRDEACGKETPAGYAGLCQAHYKEYLVSLINAHSLDPATLYEVEELETATERYLHVRPQPLAGEDPPAYQARLLQKLTEEVPLGQSIPRRRK
  n_term: 1
  c_term: 379
  author: Foo Bar
```
and the following hdx input 
[hoipsim1.csv](https://github.com/Jhsmit/PyHDX/files/9698223/hoipsim1.csv)

The outputted error when I edit your python script is:

```py
input_dir =  Path() / 'tests' / 'test_data' / 'input'
s = yaml.safe_load((input_dir / 'hoipsim1.yaml').read_text())
p = StateParser(state_spec=s, data_src=input_dir)
hdxm = p.load_hdxm("Hoip_testing")
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [35], line 4
      2 s = yaml.safe_load((input_dir / 'hoipsim1.yaml').read_text())
      3 p = StateParser(state_spec=s, data_src=input_dir)
----> 4 hdxm = p.load_hdxm("Hoip_testing")

File ~\Desktop\2022-sublocalisationHDX\PyHDX\pyhdx\batch_processing.py:145, in StateParser.load_hdxm(self, state, **kwargs)
    142     else:
    143         control_0 = None
--> 145     pmt.set_control(
    146         control_1=(control_state, control_exposure), control_0=control_0
    147     )
    148 # Flat back exchange percentage for all peptides
    149 elif "be_percent" in state_dict.keys():

File ~\Desktop\2022-sublocalisationHDX\PyHDX\pyhdx\models.py:394, in PeptideMasterTable.set_control(self, control_1, control_0)
    391     raise ValueError("FD control has duplicate entries") from e
    393 if fd_df.size == 0:
--> 394     raise ValueError(
    395         f"No matching peptides with state {control_1[0]} and exposure {control_1[1]}"
    396     )
    398 try:
    399     if control_0 is None:

ValueError: No matching peptides with state WT and exposure 30
```
If I look at my data there is clearly a state WT and exposure equal to 30. Could you point me in a direction to help me debug?
